name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ,dev]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make check
      run: |
          make check TARGET=testMultiply
          make check TARGET=testInverse
          make check TARGET=testAffine
          make check TARGET=Test1
          make check TARGET=testSubbytes 
          make check TARGET=testMixcolumns
          make check TARGET=testRoundkey
          make check TARGET=testSubbytes
          make check TARGET=testShiftrows
          make check TARGET=testMixcolumns
          make check TARGET=Test1
          make check TARGET=testFinverse
          make check TARGET=testfinverse
          make check TARGET=testInvshiftrows 
