name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ,dev]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make check
      run: |
          make check TARGET=testMultiply
          make check TARGET=testInverse
